// API layer for the fuss agent service. Schemas are derived from the live
// OpenAPI document (`GET /openapi.yaml`, generated by mizuoai in
// fuss/command/api/api.go) and its CUE sources in
// fuss/service/agent/schema/v1 + fuss/package/{agent,mcpx,skillx}.
//
// Every operation follows the protobuf RPC shape: one <op>Request
// message in, one <op>Response message out, both zod-validated at the
// boundary (see ../rpc.ts). Responses are validated at the boundary;
// unknown fields on config objects survive parsing (loose schemas) so
// the draft/wire editing model can carry fields it does not manage.

import { z } from "zod";
import {
  type AgentConfig,
  agentConfigSchema,
} from "../../package/agent/config";
import { defineRpc } from "../rpc";

export type { AgentConfig } from "../../package/agent/config";
export type { McpConfig, McpTransport } from "../../package/mcpx/config";
export type { SkillConfig } from "../../package/skillx/config";
export { agentConfigSchema };

const timestamp = z.iso.datetime({ offset: true });

// --- resource messages -------------------------------------------------

export const projectSchema = z.object({
  id: z.uuid(),
  source: z.string(),
  external_id: z.string(),
  name: z.string(),
  config: agentConfigSchema,
  revision: z.number().int().nonnegative(),
  created_at: timestamp,
  updated_at: timestamp,
});
export type Project = z.infer<typeof projectSchema>;

export const sessionNameSchema = z.string().min(1).max(64);

export const sessionSchema = z.object({
  id: z.uuid(),
  name: sessionNameSchema.optional(),
  project_id: z.uuid(),
  external_id: z.string().optional(),
  config: agentConfigSchema,
  next_sequence: z.number().int().nonnegative(),
  revision: z.number().int().nonnegative(),
  created_at: timestamp,
  updated_at: timestamp,
  last_activity_at: timestamp,
});
export type Session = z.infer<typeof sessionSchema>;

// --- pagination ---------------------------------------------------------

const pageSize = z.number().int().min(1).default(20);
const pageToken = z.string().default("");

// --- listProjects --------------------------------------------------------

export const listProjectsRequestSchema = z.object({
  page_size: pageSize,
  page_token: pageToken,
});
export type ListProjectsRequest = z.input<typeof listProjectsRequestSchema>;
export const listProjectsResponseSchema = z.object({
  projects: z.array(projectSchema),
  next_page_token: z.string(),
});
export type ListProjectsResponse = z.infer<typeof listProjectsResponseSchema>;

export const listProjects = defineRpc({
  service: "agent",
  name: "listProjects",
  requestSchema: listProjectsRequestSchema,
  responseSchema: listProjectsResponseSchema,
  path: (req) =>
    `/projects?page_size=${req.page_size}&page_token=${encodeURIComponent(req.page_token)}`,
});

// The service exposes no GET /projects/{id}; resolve one project by
// scanning the (small, most-recently-updated-first) project pages.
export async function findProject({ id }: { id: string }) {
  let page_token = "";
  do {
    const result = await listProjects({ page_token });
    const found = result.projects.find((item) => item.id === id);
    if (found) return found;
    page_token = result.next_page_token;
  } while (page_token);
  return null;
}

// --- listSessions --------------------------------------------------------

export const listSessionsRequestSchema = z.object({
  project_id: z.string(),
  page_size: pageSize,
  page_token: pageToken,
});
export type ListSessionsRequest = z.input<typeof listSessionsRequestSchema>;
export const listSessionsResponseSchema = z.object({
  sessions: z.array(sessionSchema),
  next_page_token: z.string(),
});
export type ListSessionsResponse = z.infer<typeof listSessionsResponseSchema>;

export const listSessions = defineRpc({
  service: "agent",
  name: "listSessions",
  requestSchema: listSessionsRequestSchema,
  responseSchema: listSessionsResponseSchema,
  path: (req) =>
    `/projects/${encodeURIComponent(req.project_id)}/sessions?page_size=${req.page_size}&page_token=${encodeURIComponent(req.page_token)}`,
});

// --- getSession ----------------------------------------------------------

export const getSessionRequestSchema = z.object({
  session_id: z.string(),
});
export type GetSessionRequest = z.input<typeof getSessionRequestSchema>;
export const getSessionResponseSchema = sessionSchema;
export type GetSessionResponse = z.infer<typeof getSessionResponseSchema>;

export const getSession = defineRpc({
  service: "agent",
  name: "getSession",
  requestSchema: getSessionRequestSchema,
  responseSchema: getSessionResponseSchema,
  path: (req) => `/sessions/${encodeURIComponent(req.session_id)}`,
});

// --- createProject --------------------------------------------------------

export const createProjectRequestSchema = z.object({
  source: z.string().min(1),
  name: z.string().min(1),
  external_id: z.string().optional(),
});
export type CreateProjectRequest = z.input<typeof createProjectRequestSchema>;
export const createProjectResponseSchema = projectSchema;
export type CreateProjectResponse = z.infer<typeof createProjectResponseSchema>;

export const createProject = defineRpc({
  service: "agent",
  name: "createProject",
  method: "POST",
  requestSchema: createProjectRequestSchema,
  responseSchema: createProjectResponseSchema,
  path: () => "/projects:create",
  body: (req) => req,
});

// --- createSession --------------------------------------------------------

export const createSessionRequestSchema = z.object({
  project_id: z.string(),
  name: sessionNameSchema.optional(),
});
export type CreateSessionRequest = z.input<typeof createSessionRequestSchema>;
export const createSessionResponseSchema = sessionSchema;
export type CreateSessionResponse = z.infer<typeof createSessionResponseSchema>;

export const createSession = defineRpc({
  service: "agent",
  name: "createSession",
  method: "POST",
  requestSchema: createSessionRequestSchema,
  responseSchema: createSessionResponseSchema,
  path: (req) => `/projects/${encodeURIComponent(req.project_id)}/sessions`,
  body: (req) => (req.name === undefined ? {} : { name: req.name }),
});

// --- updateProject --------------------------------------------------------

export const updateProjectRequestSchema = z.object({
  project: projectSchema,
  update_masks: z.array(z.string()),
});
export type UpdateProjectRequest = z.input<typeof updateProjectRequestSchema>;
export const updateProjectResponseSchema = projectSchema;
export type UpdateProjectResponse = z.infer<typeof updateProjectResponseSchema>;

export const updateProject = defineRpc({
  service: "agent",
  name: "updateProject",
  method: "PATCH",
  requestSchema: updateProjectRequestSchema,
  responseSchema: updateProjectResponseSchema,
  path: (req) => `/projects/${encodeURIComponent(req.project.id)}`,
  body: (req) => req,
});

// --- updateSession --------------------------------------------------------

export const updateSessionRequestSchema = z.object({
  session: sessionSchema,
  update_masks: z.array(z.string()),
});
export type UpdateSessionRequest = z.input<typeof updateSessionRequestSchema>;
export const updateSessionResponseSchema = sessionSchema;
export type UpdateSessionResponse = z.infer<typeof updateSessionResponseSchema>;

export const updateSession = defineRpc({
  service: "agent",
  name: "updateSession",
  method: "PATCH",
  requestSchema: updateSessionRequestSchema,
  responseSchema: updateSessionResponseSchema,
  path: (req) => `/sessions/${encodeURIComponent(req.session.id)}`,
  body: (req) => req,
});

// --- clearSession ---------------------------------------------------------

export const clearSessionRequestSchema = z.object({
  session_id: z.string(),
});
export type ClearSessionRequest = z.input<typeof clearSessionRequestSchema>;
export const clearSessionResponseSchema = z.object({});
export type ClearSessionResponse = z.infer<typeof clearSessionResponseSchema>;

export const clearSession = defineRpc({
  service: "agent",
  name: "clearSession",
  method: "POST",
  requestSchema: clearSessionRequestSchema,
  responseSchema: clearSessionResponseSchema,
  path: (req) => `/sessions/${encodeURIComponent(req.session_id)}/clear`,
});

export function configChanges(before: AgentConfig, after: AgentConfig) {
  return (Object.keys(after) as (keyof AgentConfig)[])
    .filter((key) => JSON.stringify(before[key]) !== JSON.stringify(after[key]))
    .map((key) => `config.${key}`);
}
