// API layer for the fuss agent service. Schemas are derived from the live
// OpenAPI document (`GET /openapi.yaml`, generated by mizuoai in
// fuss/command/api/api.go) and its CUE sources in
// fuss/service/agent/schema/v1 + fuss/package/{agent,mcpx,skillx}.
//
// Responses are validated at the boundary; unknown fields on config objects
// survive parsing (loose schemas) so the draft/wire editing model can carry
// fields it does not manage.

import { z } from "zod";
import {
  type AgentConfig,
  agentConfigSchema,
} from "../../package/agent/config";

export type { AgentConfig } from "../../package/agent/config";
export type { McpConfig, McpTransport } from "../../package/mcpx/config";
export type { SkillConfig } from "../../package/skillx/config";
export { agentConfigSchema };

const timestamp = z.iso.datetime({ offset: true });

export const projectSchema = z.object({
  id: z.uuid(),
  source: z.string(),
  external_id: z.string(),
  name: z.string(),
  config: agentConfigSchema,
  revision: z.number().int().nonnegative(),
  created_at: timestamp,
  updated_at: timestamp,
});

export type Project = z.infer<typeof projectSchema>;

export const sessionNameSchema = z.string().min(1).max(64);

export const sessionSchema = z.object({
  id: z.uuid(),
  name: sessionNameSchema.optional(),
  project_id: z.uuid(),
  external_id: z.string().optional(),
  config: agentConfigSchema,
  next_sequence: z.number().int().nonnegative(),
  revision: z.number().int().nonnegative(),
  created_at: timestamp,
  updated_at: timestamp,
  last_activity_at: timestamp,
});

export type Session = z.infer<typeof sessionSchema>;

export const listProjectsResponseSchema = z.object({
  projects: z.array(projectSchema),
  next_page_token: z.string(),
});

export const listSessionsResponseSchema = z.object({
  sessions: z.array(sessionSchema),
  next_page_token: z.string(),
});

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
  }
}

export class SchemaError extends Error {
  constructor(
    message: string,
    public cause: z.ZodError,
  ) {
    super(message);
  }
}

export async function request<S extends z.ZodType>(
  path: string,
  schema: S,
  init: { method?: "GET" | "POST" | "PATCH" | "DELETE"; body?: unknown } = {},
): Promise<z.output<S>> {
  const { method = "GET", body } = init;
  const response = await fetch(`/api/agent${path}`, {
    method,
    headers:
      body === undefined ? undefined : { "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (!response.ok) {
    const messages: Record<number, string> = {
      401: "Authentication failed. Check the dashboard’s service token.",
      403: "Access to this resource was denied.",
      404: "This resource or API endpoint is unavailable.",
      409: "The resource changed or is busy. Refresh and try again.",
    };
    throw new ApiError(
      response.status,
      messages[response.status] ??
        `Request failed (${response.status}). Your changes have not been confirmed.`,
    );
  }
  const parsed = schema.safeParse(await response.json());
  if (!parsed.success) {
    console.error("Fuss API response failed schema validation", parsed.error);
    throw new SchemaError(
      "The Fuss API returned data in an unexpected format.",
      parsed.error,
    );
  }
  return parsed.data;
}

export function listProjects(pageToken = "") {
  return request(
    `/projects?page_size=20&page_token=${encodeURIComponent(pageToken)}`,
    listProjectsResponseSchema,
  );
}

// The service exposes no GET /projects/{id}; resolve one project by scanning
// the (small, most-recently-updated-first) project pages.
export async function findProject(id: string) {
  let token = "";
  do {
    const result = await listProjects(token);
    const found = result.projects.find((item) => item.id === id);
    if (found) return found;
    token = result.next_page_token;
  } while (token);
  return null;
}

export function listSessions(projectId: string, pageToken = "") {
  return request(
    `/projects/${encodeURIComponent(projectId)}/sessions?page_size=20&page_token=${encodeURIComponent(pageToken)}`,
    listSessionsResponseSchema,
  );
}

export function getSession(sessionId: string) {
  return request(`/sessions/${encodeURIComponent(sessionId)}`, sessionSchema);
}

export function createProject(body: {
  source: string;
  name: string;
  external_id?: string;
}) {
  return request("/projects:create", projectSchema, { method: "POST", body });
}

export function createSession(projectId: string, body: { name?: string }) {
  return request(
    `/projects/${encodeURIComponent(projectId)}/sessions`,
    sessionSchema,
    { method: "POST", body },
  );
}

export function updateProject(project: Project, updateMasks: string[]) {
  return request(`/projects/${encodeURIComponent(project.id)}`, projectSchema, {
    method: "PATCH",
    body: { project, update_masks: updateMasks },
  });
}

export function updateSession(session: Session, updateMasks: string[]) {
  return request(`/sessions/${encodeURIComponent(session.id)}`, sessionSchema, {
    method: "PATCH",
    body: { session, update_masks: updateMasks },
  });
}

export function clearSession(sessionId: string) {
  return request(
    `/sessions/${encodeURIComponent(sessionId)}/clear`,
    z.object({}),
    { method: "POST" },
  );
}

export function configChanges(before: AgentConfig, after: AgentConfig) {
  return (Object.keys(after) as (keyof AgentConfig)[])
    .filter((key) => JSON.stringify(before[key]) !== JSON.stringify(after[key]))
    .map((key) => `config.${key}`);
}
